export const AVIATION_WFS_LAYERS = [
  {
    id: 'fir',
    nameKo: 'FIR',
    nameEn: 'FIR',
    sourceId: 'wfs-fir',
    fillLayerId: 'wfs-fir-fill',
    lineLayerId: 'wfs-fir-line',
    typeName: 'lt_c_aisfirc',
    color: '#2563eb',
    defaultVisible: false,
    fillOpacity: 0,
    lineOpacity: 0.9,
    lineWidth: 2,
  },
  {
    id: 'ctr',
    nameKo: 'CTR',
    nameEn: 'CTR',
    sourceId: 'wfs-ctr',
    fillLayerId: 'wfs-ctr-fill',
    lineLayerId: 'wfs-ctr-line',
    typeName: 'lt_c_aisctrc',
    color: '#7c3aed',
    defaultVisible: false,
    fillOpacity: 0.04,
    lineOpacity: 0.85,
    lineWidth: 1.5,
  },
  {
    id: 'tma',
    nameKo: 'TMA',
    nameEn: 'TMA',
    sourceId: 'wfs-tma',
    fillLayerId: 'wfs-tma-fill',
    lineLayerId: 'wfs-tma-line',
    typeName: 'lt_c_aistmac',
    color: '#0891b2',
    defaultVisible: false,
    fillOpacity: 0.03,
    lineOpacity: 0.85,
    lineWidth: 1.5,
  },
  {
    id: 'restricted',
    nameKo: 'Restricted',
    nameEn: 'Restricted',
    sourceId: 'wfs-restricted',
    fillLayerId: 'wfs-restricted-fill',
    lineLayerId: 'wfs-restricted-line',
    typeName: 'lt_c_aisresc',
    color: '#ea580c',
    defaultVisible: false,
    fillOpacity: 0.05,
    lineOpacity: 0.9,
    lineWidth: 1.5,
  },
  {
    id: 'prohibited',
    nameKo: 'Prohibited',
    nameEn: 'Prohibited',
    sourceId: 'wfs-prohibited',
    fillLayerId: 'wfs-prohibited-fill',
    lineLayerId: 'wfs-prohibited-line',
    typeName: 'lt_c_aisprhc',
    color: '#dc2626',
    defaultVisible: false,
    fillOpacity: 0.06,
    lineOpacity: 0.9,
    lineWidth: 1.7,
  },
  {
    id: 'danger',
    nameKo: 'Danger',
    nameEn: 'Danger',
    sourceId: 'wfs-danger',
    fillLayerId: 'wfs-danger-fill',
    lineLayerId: 'wfs-danger-line',
    typeName: 'lt_c_aisdngc',
    color: '#d97706',
    defaultVisible: false,
    fillOpacity: 0.05,
    lineOpacity: 0.9,
    lineWidth: 1.5,
  },
  {
    id: 'airway',
    nameKo: 'Airway',
    nameEn: 'Airway',
    sourceId: 'wfs-airway',
    lineLayerId: 'wfs-airway-line',
    typeName: 'lt_l_aispath',
    color: '#16a34a',
    defaultVisible: false,
    lineOpacity: 0.9,
    lineWidth: 1.4,
  },
]

export function buildWfsUrl(typeName, vworldKey, domain) {
  const params = new URLSearchParams({
    SERVICE: 'WFS',
    VERSION: '1.1.0',
    REQUEST: 'GetFeature',
    TYPENAME: typeName,
    SRSNAME: 'EPSG:4326',
    OUTPUT: 'application/json',
    KEY: vworldKey,
    DOMAIN: domain,
  })

  return `/vworld-wfs?${params.toString()}`
}
